spring.output.ansi.enabled: ALWAYS
spring.jpa:
  show-sql: true
  database: MYSQL
  properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  hibernate:
    ddl-auto: update
    naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy

spring.datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver #需要 8.0+的 mysql-connector-java
  url: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&&allowPublicKeyRetrieval=true
  username: root
  password: 123456